[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
auction = "HJdFhhRi3Z3ipPjjbeoXu8x5nBHj7rTaU8D499gLWqqL"
escrow = "8jR5GeNzeweq35Uo84kGP3v1NcBaZWH5u62k7PxN4T2y"
raffle = "AtbQBffhFkabRYCSTSa8BEjrCcV6tnD2AhJoNWSuBUvq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy = "anchor build && anchor deploy --provider.cluster devnet"
test = "npx tsx create-codama-client.ts; npx tsx --test --test-reporter=spec tests/*.ts"
