[toolchain]
anchor_version = "0.30.1"

[features]
resolution = false
skip-lint = false

[programs.devnet]
auction = "HJdFhhRi3Z3ipPjjbeoXu8x5nBHj7rTaU8D499gLWqqL"
escrow = "33umURgaFrrQvJ8K7XrFXfVyUZsp3amfRBqyuEvPP5Wu"
raffle = "AtbQBffhFkabRYCSTSa8BEjrCcV6tnD2AhJoNWSuBUvq"
swap = "BLyc8iNGvz1mYRWGZdRku1fAQdhKLpMatX4DKf2FREPt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy = "anchor build && anchor deploy --provider.cluster devnet"
test = "npx tsx create-codama-client.ts; npx tsx --test --test-reporter=spec tests/*.ts"
